cloudflare_token: ENC[AES256_GCM,data:URetl6kKM3r+GIrLFgZvFvkU4xVX91xG5gwVKdaLbPVET+F8hDkpBkCZnpIwtTnrAAM4EBdbLgF5fj3EfMBdZ2U=,iv:ASw91Afj+O2Vot1pKEgj4NIE0ECtLBz7KdTFD2SZcRw=,tag:ZJ/wgHmVDiWU8KqnP9IAVQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18qf8zg4y6w298xmzrka8kpad0s7k2sueccnwep49xgv3rtx82gwqzgruyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJVzFQbjQrZG9lamtUTGN6
            aEJ2RXJBa0R6cjVkVjFjQy95cm4yN1BnSVdFCmxSdXBSTFRENUxZbWpsTStOYlls
            MTc0ZDdzT1FZWC9iOXE4THB5Tk1KelkKLS0tIGg2Qyt1Y05Qbk5DeGZLSzhCUnNE
            eDZNdDlNOThuZHVPek9STjZ2VHdTMTgKrN9AufW6oJW4ZFcKF6eVi1sCNTSNW9Oh
            ivaZnrdHam/XHuvguOXj/xhJHoS46hgfmFnLPiHXwO7cvIq4e7xkJw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14yna8d64kwwefxs8lrtzmd5v6g5e5r5hg4shnu5s5qcveur6739qx8creq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAySEFFT09GbzZjMThMcUpX
            Rm9zOUUyQlcvUWRTb3JDb3ZSZXRpRzRsdUhVCktBNytVRGRBV1k3QnZ2dDgvM2xz
            K3E4UTFKeGxPcy9wMWV1a01tcjR0Sk0KLS0tIFhaNmMvN0p4Y1hQaGxlbU1nVTJx
            bis3UXlsdC9xQTFIMzBPelMyOG1KUkkKqHRZA2/CEXz+Z+QSkCLd+yJy2r/MDDyP
            9MXDDdkLWsBs03HabluR8Uw3hjKIC0QV0vG9cEk/dGDOn5XpRaNy/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-08T06:33:41Z"
    mac: ENC[AES256_GCM,data:CfqbcTaA12r+U0dWLlBK+HaC/rpR1EHXMfvfGSGXVeMsAIR0QTbtuWT2epzd2WN3yemuYbp0DQVr+cV2TVuJxjKfvG+i3PIJn/D6RSa8qJVZFHawUztRC894j7haMylcoDpc2y29y0VCGEJ5XNEPVVi+XhX91ocOfaheFjrs5cE=,iv:arMh4mnPHspqfVAFZdheiVlptIAAWrITJ98VzeDTX+I=,tag:Nd5qlh0IGaZIFNx/N5R1VA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
