name: Update
on:
  schedule:
    - cron: "0 0 */2 * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Configure Git
        run: |
          git config --global user.email "1sixth@shinta.ro"
          git config --global user.name "1sixth"
      - name: Update Nix Flake
        run: nix flake update --commit-lock-file
      - name: Git Push
        run: git push
